include ../make.config

all : $(incdir)/tensor.hpp \
	$(incdir)/alignment.hpp 

$(incdir)/tensor.hpp: tensor.hpp
	cp tensor.hpp $(incdir)/tensor.hpp

$(incdir)/alignment.hpp: alignment.hpp
	cp alignment.hpp $(incdir)/alignment.hpp

clean :
